name: 'reverse-proxy-app'

services:
  reverse-proxy-app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      npm run start
    ports:
      - "8080:8080"
      - "80:80"
    network_mode:
      bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/home/app